include gruvbox_dark.conf
background_opacity 0.9

font_family      Cascadia Code
bold_font        Cascadia Code Bold
italic_font      Cascadia Code Italic
bold_italic_font Cascadia Code Bold Italic

symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols
narrow_symbols U+E0A0-U+E0A3,U+E0C0-U+E0C7 1

map alt+1 disable_ligatures_in active always
map alt+2 disable_ligatures_in all never
map alt+3 disable_ligatures_in tab cursor

font_size 12

enable_audio_bell no


scrollback_lines 5000

