no-osd-bar 
save-position-on-quit
no-border 

# decode-substitle
vo=opengl:gamma-auto:icc-profile-auto
hwdec=auto-safe
autofit-larger=78%
playcache=8192
lang=zh,chi
video-sync=display-resample

profile=gpu-hd
icc-profile-auto
icc-3dlut-size=256x256x256
blend-subtitles=video

sub-codepage=enca:zh:utf8
sub-auto=fuzzy
sub-text-font-size=40
sub-text-shadow-offset=0
sub-text-color="#ffffffff"
#sub-text-font="STZhongsong"
sub-codepage=utf8:gb18030

screenshot-template=mpv-screenshot-%f-%ws
screenshot-format=png

#osd-font="STZhongsong"
osd-font-size=28

font="DejaVu Sans"
font_mono="DejaVu Sans Mono"
sub-text-font="Noto Sans"

# screenshot
screenshot-format=png
screenshot-directory=~/Pictures/mpvscreenshots/

keep-open=no


--script=~/.config/mpv/autoload.lua
