no-osd-bar 
save-position-on-quit
no-border 

# decode-substitle
vo=gpu
gpu-api=vulkan
profile=gpu-hq
hwdec=auto
autofit-larger=78%
video-sync=display-resample

icc-profile-auto
icc-3dlut-size=256x256x256
blend-subtitles=video

sub-codepage=enca:zh:utf8
sub-auto=fuzzy
sub-font-size=40
sub-shadow-offset=0
sub-color="#ffffffff"
#sub-text-font="STZhongsong"
sub-codepage=utf8:gb18030

screenshot-template=mpv-screenshot-%f-%ws
screenshot-format=png

#osd-font="STZhongsong"
osd-font-size=28
osd-font="DejaVu Sans"
sub-font="Noto Sans"

# screenshot
screenshot-format=png
screenshot-directory=~/Pictures/mpvscreenshots/

keep-open=no


--script=~/.config/mpv/autoload.lua
