[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 1
label-mode-foreground = #000
label-mode-background = ${colors.primary}

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 1

label-unfocused = %index%
label-unfocused-padding = 1

label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

; label-separator = | 


[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%


################################################################################

[module/date]
;https://github.com/jaagr/polybar/wiki/Module:-date
type = internal/date
interval = 5
date = " %Y-%m-%d%"
date-alt = " %d-%m-%Y"
time-alt = %a %b %d - %I:%M%p
time = %H:%M
format-prefix = ""
format-prefix-foreground = ${colors.foreground}
;format-prefix-background = ${colors.cyan}
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-padding = 0 
format-prefix-padding = 0 
label =%{T3} %time% %{T-}

################################################################################

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %free%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

################################################################################

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%


################################################################################

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ""
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%


################################################################################

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected


################################################################################

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
# ; label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%


################################################################################

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

################################################################################

[module/pacman-updates]
type = custom/script
exec = pacman -Qu | wc -l
interval = 300
label = %output%
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = " "
format-prefix-foreground = #FFBB00
; format-underline = #FFBB00

################################################################################

[module/volume]
type = internal/pulseaudio
use-ui-max = true
interval = 5

format-volume = <ramp-volume> <label-volume>

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

label-muted = muted
label-muted-foreground = #666

format-foreground = ${colors.foreground}
################################################################################

[module/battery]
type = internal/battery
full-at = 99
low-at = 5

battery = BAT0
adapter = ADP1
poll-interval = 1

time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging>  <label-charging>


; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-discharging = <ramp-capacity>  <label-discharging>


; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = %time% (%consumption%)
label-discharging = %time% (%percentage%%)

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10


; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750

################################################################################

[module/powermenu]
type = custom/menu
menu-0-0 = Poweroff
menu-0-0-exec = poweroff
menu-0-1 = Suspend
menu-0-1-exec = systemctl suspend

################################################################################

[settings]
screenchange-reload = true
pseudo-transparency = true
