
# The following lines were added by compinstall

autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Enable colors and change prompt:
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

# add a command line to the shells history without executing it
commit-to-history () {
       print -s ${(z)BUFFER}
       zle send-break
}

zle -N commit-to-history
bindkey -M viins "^x^h" commit-to-history
bindkey -M emacs "^x^h" commit-to-history
bindkey "^A" vi-beginning-of-line
bindkey "^E" vi-end-of-line
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "\e[3~" delete-char

function zsh_stats() {
    fc -l 1 | awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl |  head -n20
}

EDITOR="vim"
export EDITOR

function ranger-cd {
    tempfile="$(mktemp)"
    /usr/bin/ranger --choosedir="$tempfile" "${@:-$(pwd)}"
    test -f "$tempfile" &&
    if [ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]; then
	cd -- "$(cat "$tempfile")"
    fi
    rm -f -- "$tempfile"
}

HISTFILE=~/.cache/zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

set backspace=indent,eol,start

# set alias
alias ls='exa -gb'
alias ll='ls -l'
alias la='ls -laa'
alias lh='ls -lh'
alias grep='grep --color'
alias g="git-annex"
alias k="kde-open5"
alias x="xdg-open"

alias ~="cd ~"
alias ..="cd .."

alias start="sudo systemctl start"
alias stop="sudo systemctl stop"
alias restart="sudo systemctl restart"
alias status="sudo systemctl status"
alias enable="sudo systemctl enable"
alias disable="sudo systemctl disable"

alias ytdl="yt-dlp"
alias tlmgr="tllocalmgr"

alias proxy="proxychains4"
alias pmpv="proxychains4 mpv"

alias dotfiles="cd ~/wkspace/dotfiles"

alias orphans="sudo pacman -Qtdq | sudo pacman -Rns -"
alias pupgrade="proxy sudo pacman -Syu"
alias install="sudo pacman -S"
alias upgrade="sudo pacman -Syu"
alias remove="sudo pacman -Rns"
alias Ss="pacman -Ss"

alias vim="nvim"
alias cdd="cd ~/wkspace/dotfiles"

export LESS="-R -N"


export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
