require("core.options")
require("core.keymaps")
require("core.colorscheme")

require("plugins-setup")
require("plugins.cmp")
require("plugins.lualine")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.nvimTree")
require("plugins.telescope")
require("plugins.indent-blankline")
require("plugins.barbar")

require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
