set preview_script /home/yuki/.config/ranger/data/scope.sh
set preview_images true
set preview_images_method ueberzug 
set column_ratios 1,6,4

default_linemode devicons

set status_bar_on_top false
set update_tmux_title true
set sort_directories_first true
